####
#
# docker-compose global prévu pour être utilisé avec les 
# variables d'environnement définies dans les images
# attention : avant d'utiliser cette image, 
# il faut avoir utilisé docker-init.yml
#
####

version: "3.6"
services:
  traefik:
    image: uepal_test/traefik_docker
    hostname: traefik
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:18080:8080"
    depends_on:
      - civihttpd
    networks:
      civinet:
        aliases:
          - traefik
  civihttpd:
    image: uepal_test/httpd
    hostname: civihttpd
    depends_on:
      - civirouter
      - civimail
    networks:
      civinet:
        aliases:
          - civicrm.test
          - civihttpd
    volumes:
      - type: volume
        source: civicomp_filevol
        target: /app/web/sites
        volume:
          nocopy: true
      - type: volume
        source: civicomp_privatevol
        target: /app/private
        volume:
          nocopy: true
      - type: volume
        source: civicomp_dbsockvol
        target: /var/run/mysqld
        volume:
          nocopy: true
      - type: volume
        source: civicomp_certvol
        target: /etc/ssl/certs
        volume:
          nocopy: true

  civirouter:
     image: uepal_test/mysql_tls_router
     hostname: civirouter
     depends_on:
       - cividb
     networks:
       dbnet:
         aliases:
         - civirouter
     volumes:
      - type: volume
        source: civicomp_dbsockvol
        target: /SOCK
        volume:
          nocopy: true

  cividb:
    image: uepal_test/mysql_tls_server
    hostname: cividb
#    command: ["/bin/sh","-c","while true;do  sleep 3600;done"]
    networks:    
      dbnet:
        aliases:
        - civicrmdb
    volumes:
      - type: volume
        source: civicomp_dbvol
        target: /var/lib/mysql
        volume:
          nocopy: true

  civimail:
    image: uepal_test/test_opensmtpd_dovecot
    hostname: civimail
    networks:
      civinet:
        aliases:
        - imap
        - smtp

  civitools:
    image: uepal_test/tools
    hostname: civitools
    depends_on:
      - civirouter
      - civimail
    networks:
      civinet:
        aliases:
        - civitools
    command: ["/bin/sh","-c","while true;do  sleep 3600;done"]
    volumes:
      - type: volume
        source: civicomp_dbsockvol
        target: /var/run/mysqld
        volume:
          nocopy: true
      - type: volume
        source: civicomp_filevol
        target: /app/web/sites
        volume:
          nocopy: true
      - type: volume
        source: civicomp_privatevol
        target: /app/private
        volume:
          nocopy: true
      - type: volume
        source: civicomp_certvol
        target: /etc/ssl/certs
        volume:
          nocopy: true



networks:
  civinet:
  dbnet:
    
volumes:
  civicomp_certvol:
  civicomp_dbvol:
  civicomp_filevol:
  civicomp_privatevol:
  civicomp_dbsockvol:
    driver: local
    driver_opts:
      type: "tmpfs"
      o: "uid=999"
      device: "tmpfs"
