entryPoints:
  websecure:
    address: ":443"
    http:
      tls: {}
#  traefik:
#    address: ":8080"
providers:
  file:
   directory: "/etc/traefik/conf.d"
accessLog: {}
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
